### ISSUE TITLE
What is the "colors" script used to display the current pallette in the README 

### ISSUE THREAD

**Issue by oknozor** [arcticicestudio/nord-alacritty#15]
Sorry to bother you but I've been searching for this without success.

**Comment by oknozor** [comment]
After hour of search I found it, https://github.com/jsvensson/colortest

**Comment by arcticicestudio** [comment]
I mean I simply copied and adjusted one of the script from [stark/Color-Scripts][], but the one you found it quite interesting because I 💙 Go and it uses Nord as example 😄  

[stark/Color-Scripts]: https://github.com/stark/Color-Scripts

**Comment by oknozor** [comment]
I was frustrated with go bin not being in my path so I wrote this https://github.com/oknozor/colo-rs/ :rofl:
