### ISSUE TITLE
Can you specify in brief where is the file alacritty.yml  located ??

### ISSUE THREAD

**Issue by saurabhmehta1601** [arcticicestudio/nord-alacritty#18]

**Comment by arcticicestudio** [comment]
Hi @saurabhmehta1601 :wave:, thanks for your contribution :+1:

This is part of the Alacritty documentation. The link in the [“Installation“][1] section of the README also links to the [“Configuration“ section in the Alacritty GitHub repository README][2].

[1]: https://github.com/arcticicestudio/nord-alacritty#installation
[2]: https://github.com/alacritty/alacritty#configuration

**Comment by arcticicestudio** [comment]
Going to close this issue as this should answer the question. Please feel free to reply here when something is not yet clear.
