### ISSUE TITLE
Terminal configuration in screenshot?

### ISSUE THREAD

**Issue by smcallis** [arcticicestudio/nord-alacritty#19]
Sorry I know it's not an issue but don't know where else I could ask, I really like the terminal prompt in the [screenshot](https://raw.githubusercontent.com/arcticicestudio/nord-alacritty/develop/assets/scrot-hero.png), and I'm curious if that config is available somewhere.

**Comment by arcticicestudio** [comment]
Hi @smcallis  :wave:
It's [my own custom ZSH shell promt theme that you can find in my _.dotfile_ repository][1].

[1]: https://github.com/arcticicestudio/igloo/tree/414a7df82fd675/snowblocks/zsh#prompt-theme

**Comment by smcallis** [comment]
Awesome thank you!  It's very nice.
